exclude: (.github/workflows/)|(repo-cache.json)
repos:
- rev: v3.2.0
  repo: https://github.com/pre-commit/pre-commit-hooks
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
  - id: check-toml
  - id: check-json
  - id: check-merge-conflict
  - id: check-added-large-files
