# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'getoptlong'

hostname = 'nupac'
cpus = 4
mem = 4096
gui = false
provider = 'virtualbox'
box = 'generic/ubuntu2204'
version = 'latest'

opts = GetoptLong.new(
    [ '--version', '-v', GetoptLong::OPTIONAL_ARGUMENT ]
)
opts.ordering=(GetoptLong::REQUIRE_ORDER)
opts.each do |opt, arg|
    case opt
    when '--version'
        version = arg
    end
end

Vagrant.configure("2") do |config|
  if Vagrant::Util::Platform.darwin?
    if system('sysctl sysctl.proc_translated >/dev/null 2>&1')
      provider = 'parallels'
      box = 'ubuntu-22.04-arm'
    end
  end
  config.vm.synced_folder "../../", "/vagrant"
  config.vm.hostname = hostname
  config.vm.box = box
  config.vm.provider provider do |pv|
    pv.gui = gui
    pv.memory = mem
    pv.cpus = cpus
    pv.linked_clone = true
    pv.name = hostname
  end
  config.ssh.extra_args = ["-t", "cd /vagrant; nu -l"]
  end
end
