name: Bug Report
description: Create a report to help us improve
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Thank you for your bug report.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected nupac to...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add any relevant screenshots here, if any
    validations:
      required: false
  - type: textarea
    id: nuconfig
    attributes:
      label: Nu configuration
      description: "Please run `version | transpose key value | to md --pretty` and paste the output to show OS, features, etc."
      placeholder: |
        > version | transpose key value | to md --pretty
        | key                | value                                                                                                                                                                   |
        | ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
        | version            | 0.40.0                                                                                                                                                                  |
        | build_os           | linux-x86_64                                                                                                                                                            |
        | rust_version       | rustc 1.56.1                                                                                                                                                            |
        | cargo_version      | cargo 1.56.0                                                                                                                                                            |
        | pkg_version        | 0.40.0                                                                                                                                                                  |
        | build_time         | 1980-01-01 00:00:00 +00:00                                                                                                                                              |
        | build_rust_channel | release                                                                                                                                                                 |
        | features           | clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                      |
        | installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |
    validations:
      required: true
  - type: textarea
    id: nupacconfig
    attributes:
      label: Nupac configuration
      description: "Please run `nupac verison | transpose key value | to md --pretty` and paste the output to show which nupac's version are you using"
      placeholder: |
        > nupac verison | transpose key value | to md --pretty
        | key        | value                                                                  |
        | ---------- | ---------------------------------------------------------------------- |
        | long-desc  | Very long description of nushell as package manager wow so many words
         |
        | keywords   | [package|management]                                                   |
        | author     | [skelly37|Yethal]                                                      |
        | raw-url    | https://raw.githubusercontent.com/skelly37/nupac/main/modules/nupac.nu |
        | name       | nupac                                                                  |
        | os         | [android|linux|macos|windows]                                          |
        | url        | https://github.com/skelly37/nupac/blob/main/modules/nupac.nu           |
        | short-desc | package manager for nushell                                            |
        | version    | 0.1.0                                                                  |
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
