---
- name: Basic Test
  hosts: all
  become: false

  tasks:
    # - name: Run the installer
    #   raw: "fetch https://raw.githubusercontent.com/skelly37/nupac/{{ ansible_env.NUPAC_INSTALLER_BRANCH }}/installer.nu|save installer.nu; chmod +x installer.nu; nu installer.nu"
    #   args:
    #     executable: "{{ nu }}"
    #   register: installer

    # - name: Assert the installer ran successfully
    #   assert:
    #     that: '"nupac has been successfully installed" in installer.stdout'

    # - name: Assert nupac files were created
    #   block:
    #     - name: Stat files
    #       stat:
    #         path: "{{ansible_env.HOME}}/.config/nushell/scripts/{{ item }}"
    #       loop:
    #         - nupac.nu
    #         - nu-pkgs.nu
    #       register: files

    #     - name: Assert files exist
    #       assert:
    #         that: "{{ files.results | map(attribute='stat.exists') }} is all"

    - name: Get scope commands
      raw: "$nu.scope.commands|where not is_builtin|get command|to json"
      args:
        executable: "{{ nu }}"
      register: scope
      ignore_errors: true

    - name: debug scope
      debug:
        msg: "{{ scope.stdout | from_json }}"


    - name: debug binary
      debug:
        msg: "{{ nu }}"


    # - name: Assert package file was created
    #   block:
    #     - name: Stat file
    #       stat:
    #         path: "{{ansible_env.HOME}}/.config/nushell/scripts/make.nu"
    #       register: package
    #     - name: Assert make.nu exists
    #       assert:
    #         that: package.stat.exists
