---
- name: Basic Test
  hosts: all
  become: false

  tasks:
    - name: Run the installer
      raw: "nu -c (fetch https://raw.githubusercontent.com/skelly37/nupac/{{ ansible_env.NUPAC_INSTALLER_BRANCH }}/installer.nu)"
      args:
        executable: "{{ nu }}"
      register: installer

    - name: Assert the installer ran successfully
      assert:
        that: '"nupac has been successfully installed" in installer.stdout'

    - name: Assert nupac files were created
      block:
        - name: Stat files
          stat:
            path: "{{ansible_env.HOME}}/.config/nushell/scripts/{{ item }}"
          loop:
            - nupac.nu
            - nu-pkgs.nu
          register: files

        - name: Assert files exist
          assert:
            that: "{{ files.results | map(attribute='stat.exists') }} is all"

    - name: Install package
      raw: "nupac install make"
      args:
        executable: "{{ nu }}"

    - name: Assert package file was created
      block:
        - name: Stat make.nu
          stat:
            path: "{{ nushell_dir }}/scripts/make.nu"
          register: package
        - name: Assert make.nu exists
          assert:
            that: package.stat.exists
