---
- name: Converge
  hosts: all
  become: false

  tasks:
    - name: Set nushell binary as fact
      set_fact:
        nu: "{{ ansible_env.NUSHELL_INSTALL_DIR }}/nu"

    - name: Debug
      debug:
        msg: "{{ ansible_env }}"

    - name: Verify nushell is installed
      ansible.builtin.shell:
        cmd: "version|to json"
        executable: "{{ nu }}"
      changed_when: false
      register: output

    - name: Assert that version is 0.65.0
      assert:
        that: version == '0.65.0'
      vars:
        version: "{{ output.stdout | from_json | json_query('pkg_version') }}"

    # - name: Run the installer
    #   ansible.builtin.shell:
    #     cmd: "nu -c (fetch https://raw.githubusercontent.com/skelly37/nupac/{{ ansible_env.NUPAC_INSTALLER_BRANCH }}/installer.nu)"
    #     executable: "{{ nu }}"
    #   changed_when: false
    #   register: installer
    #   ignore_errors: true
