---
- name: Install package
  hosts: all
  become: false
  vars:
    package: make

  tasks:
    - name: Install package
      raw: "nupac install {{ package }}"
      args:
        executable: "{{ nu }}"

    - name: Stat {{ package }}.nu
      stat:
        path: "{{ nupac_dir }}/packages/{{ package }}/{{ package }}.nu"
      register: package_state

    - name: Stat metadata.json
      stat:
        path: "{{ nupac_dir }}/packages/{{ package }}/metadata.json"
      register: package_metadata_state

    - name: Check nu-pkgs.nu content
      slurp:
        src: "{{ nupac_dir }}/nu-pkgs.nu"
      register: nupkgs

    - name: Get nushell scope
      raw: "$nu.scope.commands|get name|to json"
      args:
        executable: "{{ nu }}"
      register: scope

    - name: Assert package file was created and not added to scope
      assert:
        that:
          - package_state.stat.exists
          - package_metadata_state.stat.exists
          - "'{{ package }}' not in {{ scope.stdout | from_json }}"
          - "'use packages/{{ package }}/{{ package }}.nu * # added automatically by nupac' not in {{ nupkgs['content'] | b64decode | split('\n') }}"
