---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:20.04
    dockerfile: Dockerfile.j2
    command: "/sbin/init"
    priviledged: false
    pre_build_image: false
    env:
      NUSHELL_INSTALL_DIR: /usr/bin
      NUSHELL_INSTALL_VERSION: 0.65.0
provisioner:
  name: ansible
  playbooks:
    converge: "${PLAYBOOK:-converge.yml}"
  inventory:
    host_vars:
      instance:
        ansible_user: ansible
