---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${DISTRO:-ubuntu:20.04}
    dockerfile: Dockerfile.j2
    tmpfs:
      - /run
      - /tmp
    pre_build_image: false
    env:
      NUSHELL_INSTALL_DIR: /usr/bin
      NUSHELL_INSTALL_VERSION: 0.65.0
      NUPAC_INSTALLER_BRANCH: ${GITHUB_HEAD_REF:-add-nu-pkgs} #CHANGE THIS TO MASTER BEFORE MERGE
      NUPAC_DEFAULT_BRANCH: ${GITHUB_HEAD_REF:-add-nu-pkgs} #CHANGE THIS TO MASTER BEFORE MERGE
provisioner:
  name: ansible
  playbooks:
    converge: "${TEST:-basic_test.yml}"
  inventory:
    host_vars:
      instance:
        ansible_user: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
