---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "ghcr.io/nupac/nupac:latest"
    pre_build_image: true
    command: ""
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    priviledged: true
    env:
      NUPAC_INSTALLER_BRANCH: ${GITHUB_HEAD_REF:-main}
      NUPAC_DEFAULT_BRANCH: ${GITHUB_HEAD_REF:-main}
      NUPAC_NO_CONFIRM: 'true'
provisioner:
  name: ansible
  playbooks:
    converge: "${TEST:-install-package.yml}"
  env:
    MOLECULE_NO_LOG: false
  inventory:
    host_vars:
      instance:
        nushell_dir: "{{ ansible_env.HOME }}/.config/nushell"
        nupac_dir: "{{ ansible_env.HOME }}/.config/nushell/nupac"
        nu: "/usr/local/bin/nu --config {{ nushell_dir }}/config.nu --env-config {{ nushell_dir }}/env.nu"
        fields:
          - 'name'
          - 'version'
          - 'author(s)'
          - 'supported OS'
          - 'description'
scenario:
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  prepare_sequence:
    - dependency
    - create
    - prepare
