- name: Test nupac command
  hosts: all
  become: false

  tasks:
    - name: Get nupac output
      raw: "nupac"
      args:
        executable: "{{ nu }}"
      register: nupac

    - name: Get nupac -h output
      raw: "nupac -h"
      args:
        executable: "{{ nu }}"
      register: nupach

    - name: Assert nupac without any flags displays help
      assert:
        that:
          - "nupac.stdout == nupach.stdout"

    - name: Get nupac -v output
      raw: "nupac -v"
      args:
        executable: "{{ nu }}"
      register: nupacv

    - name: Get nupac version output
      raw: "nupac version | get version"
      args:
        executable: "{{ nu }}"
      register: nupacversion

    - name: Assert nupac version outputs the same version as nupac -v
      assert:
        that:
          - "nupacversion.stdout == nupacv.stdout"
