---
- name: Refresh cache
  hosts: all
  become: false

  tasks:
    - name: Remove existing nupac cache
      file:
        path: "{{ nushell_dir }}/scripts/nupac.json"
        state: absent

    - name: Refresh nupac cache
      raw: "nupac refresh"
      args:
        executable: "{{ nu }}"

    - name: Stat nupac cache
      stat:
        path: "{{ nushell_dir }}/scripts/nupac.json"
      register: cache

    - name: Assert cache file exists
      assert:
        that: 'cache.stat.exists'
