---
- name: Search with & without -l flag
  hosts: all
  become: false
  vars:
    package: make

  tasks:
    - name: Search with --long
      raw: "nupac search {{ package }} --long | to json"
      args:
        executable: "{{ nu }}"
      register: searchl

    - name: Assert that long-desc was used
      assert:
        that: "'This module contains completions for make build tool' in searchl.stdout | from_json | first | json_query('description')"

    - name: Search without --long
      raw: "nupac search {{ package }} | to json"
      args:
        executable: "{{ nu }}"
      register: search

    - name: Assert that short-desc was used
      assert:
        that: "'makefile completions for nu' in search.stdout | from_json | first | json_query('description')"
