---
- name: Uninstall package
  hosts: all
  become: false
  vars:
    package: make

  tasks:
    - name: Install package
      raw: "nupac install {{ package }} -a"
      args:
        executable: "{{ nu }}"

    - name: Stat {{ package }}.nu
      stat:
        path: "{{ nupac_dir }}/packages/{{ package }}/{{ package }}.nu"
      register: package_state

    - name: Stat {{ package }}.json
      stat:
        path: "{{ nupac_dir }}/packages/{{ package }}/{{ package }}.json"
      register: package_metadata_state

    - name: Check nu-pkgs.nu content
      slurp:
        src: "{{ nupac_dir }}/nu-pkgs.nu"
      register: nupkgs

    - name: Get nushell scope
      raw: "$nu.scope.commands|get command|to json"
      args:
        executable: "{{ nu }}"
      register: scope

    - name: Assert package file was created and command was added to scope
      assert:
        that:
          - package_state.stat.exists
          - package_metadata_state.stat.exists
          - '"{{ package }}" in {{ scope.stdout | from_json }}'
          - "'use {{ nupac_dir }}/{{ package }}/{{ package }}.nu * # added automatically by nupac' in {{ nupkgs['content'] | b64decode | split('\n') }}"

    - name: Uninstall package
      raw: "nupac remove make"
      args:
        executable: "{{ nu }}"

    - name: Stat {{ package }}.nu again
      stat:
        path: "{{ nupac_dir }}/packages/{{ package }}/{{ package }}.nu"
      register: package_state

    - name: Check nu-pkgs.nu content again
      slurp:
        src: "{{ nupac_dir }}/nu-pkgs.nu"
      register: nupkgs

    - name: Get nushell scope again
      raw: "$nu.scope.commands|get command|to json"
      args:
        executable: "{{ nu }}"
      register: scope

    - name: Assert package was deleted and removed from scope
      assert:
        that:
          - not package_state.stat.exists
          - '"{{ package }}" not in {{ scope.stdout | from_json }}'
          - "'use packages/{{ package }}/{{ package }}.nu * # added automatically by nupac' not in {{ nupkgs['content'] | b64decode | split('\n') }}"
