---
- name: Use and unuse flags
  hosts: all
  become: false
  vars:
    package: make

  tasks:
    - name: Install packages
      raw: "nupac install {{ package }}"
      args:
        executable: "{{ nu }}"

    - name: Stat {{ package }}.nu
      stat:
        path: "{{ nupac_dir }}/packages/{{ package }}/{{ package }}.nu"
      register: package_state

    - name: Stat metadata.json
      stat:
        path: "{{ nupac_dir }}/packages/{{ package }}/metadata.json"
      register: package_metadata_state

    - name: Check nu-pkgs.nu content
      slurp:
        src: "{{ nupac_dir }}/nu-pkgs.nu"
      register: nupkgs

    - name: Get nushell scope
      raw: "$nu.scope.commands|get name|to json"
      args:
        executable: "{{ nu }}"
      register: scope

    - name: Assert {{ package }} files were created and not added to scope
      assert:
        that:
          - package_state.stat.exists
          - package_metadata_state.stat.exists
          - "'{{ package }}' not in {{ scope.stdout | from_json }}"
          - "'use {{ nupac_dir }}/packages/{{ package }}/{{ package }}.nu * # added automatically by nupac' not in {{ nupkgs['content'] | b64decode | split('\n') }}"

    - name: Add all packages to scope
      raw: "nupac use --all"
      args:
        executable: "{{ nu }}"

    - name: Check nu-pkgs.nu content second time
      slurp:
        src: "{{ nupac_dir }}/nu-pkgs.nu"
      register: nupkgstwo

    - name: Get nushell scope second time
      raw: "$nu.scope.commands|get name|to json"
      args:
        executable: "{{ nu }}"
      register: scopetwo

    - name: Assert {{ package }} was added to scope
      assert:
        that:
          - "'{{ package }}' in {{ scopetwo.stdout | from_json }}"
          - "'use {{ nupac_dir }}/packages/{{ package }}/{{ package }}.nu * # added automatically by nupac' in {{ nupkgstwo['content'] | b64decode | split('\n') }}"

    - name: Remove packages from scope
      raw: "nupac unuse --all"
      args:
        executable: "{{ nu }}"

    - name: Check nu-pkgs.nu content third time
      slurp:
        src: "{{ nupac_dir }}/nu-pkgs.nu"
      register: nupkgsthree

    - name: Get nushell scope third time
      raw: "$nu.scope.commands|get name|to json"
      args:
        executable: "{{ nu }}"
      register: scopethree

    - name: Assert {{ package }} was removed from scope
      assert:
        that:
          - "'{{ package }}' not in {{ scopethree.stdout | from_json }}"
          - "'use {{ nupac_dir }}/packages/{{ package }}/{{ package }}.nu * # added automatically by nupac' not in {{ nupkgsthree['content'] | b64decode | split('\n') }}"

    - name: Assert nupac was not removed from scope
      assert:
        that:
          - "'nupac' in {{ scopethree.stdout | from_json }}"
          - "'use {{ nupac_dir }}/packages/nupac/nupac.nu * # added automatically by nupac' in {{ nupkgsthree['content'] | b64decode | split('\n') }}"

    - name: Remove nupac from scope
      raw: "nupac unuse --self"
      args:
        executable: "{{ nu }}"

    - name: Check nu-pkgs.nu content fourth time
      slurp:
        src: "{{ nupac_dir }}/nu-pkgs.nu"
      register: nupkgsfour

    - name: Get nushell scope fourth time
      raw: "$nu.scope.commands|get name|to json"
      args:
        executable: "{{ nu }}"
      register: scopefour

    - name: Assert nupac was removed from scope
      assert:
        that:
          - "'nupac' not in {{ scopefour.stdout | from_json }}"
          - "'use {{ nupac_dir }}/packages/nupac/nupac.nu * # added automatically by nupac' not in {{ nupkgsfour['content'] | b64decode | split('\n') }}"