---
name: Delete temporary docker image
'on':
  pull_request:
    types:
      - closed

permissions:
  contents: read
  packages: write|read|delete

env:
  image_name: ${{ github.repository }}

jobs:
  delete-temp-image:
    name: Delete image after PR was closed
    runs-on: ubuntu-latest
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with:
          owner: nupac
          name: nupac
          token: ${{ secrets.RELEASE_ACTION_TOKEN }}
          tag: PR-${{github.event.pull_request.number}}
