---
name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: nu {0}

jobs:
  generate-repo-index:
    name: Generate repo index
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Nu
        uses: hustcer/setup-nu@main
        with:
          version: '0.66.2'
      - name: Update nuon
        run: ./generate-repo-cache.nu
# action does not perform git push yet
  pre-commit-fix:
    name: Fix with pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install pre-commit
        run: |
          pip3 install pre-commit
          pre-commit install
      - name: Run pre-commit
        run: pre-commit run --all-files -v
  push-changes:
    name: Push the changes
    runs-on: ubuntu-latest
    needs: [generate-repo-index, pre-commit-fix]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup git & commit changes
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "RELEASE"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

