---
name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-repo-index:
    name: Generate repo index
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Nu
        uses: hustcer/setup-nu@main
        with:
          version: '0.63.0'
      - name: Update json
        run: ./generate-repo-cache.nu
# action does not perform git push yet
